---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        otp_vsn: [19.3, 20.3, 21.0, 22.0]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - run: rebar3 --version
      - run: rebar3 eunit
      - run: '[[ 0 -eq $(git --no-pager diff | wc -l) ]]'
