---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    container:
      image: erlang:${{matrix.otp_vsn}}
    strategy:
      matrix:
        otp_vsn: ["19.0", "19.3",
                  "20.0", "20.1.7", "20.3.8.22",
                  "21.0.9", "21.1.4", "21.2.7", "21.3.8.1",
                  "22.0.7", "22.2.8", "22.3.4",
                  "23.0.2", "23.2"]
        os: [ubuntu-latest]
    steps:
      - run: |
          apt-get update
          apt-get -y install tcl tcl-dev gettext
          cd /usr/src/
          wget https://github.com/git/git/archive/v2.18.0.tar.gz -O git.tar.gz
          tar -xf git.tar.gz
          cd git-*
          make prefix=/usr/local all
          make prefix=/usr/local install
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: rebar3 --version
      - run: rebar3 eunit
      - run: rebar3 dialyzer
      - shell: bash
        run: '[[ 0 -eq $(git --no-pager diff | wc -l) ]]'
