---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: OTP ${{matrix.otp}}
    runs-on: ubuntu-latest
    # enable this to test all OTP versions at once regardless the errors
    # continue-on-error: true
    container:
      image: erlang:${{matrix.otp}}
    strategy:
      matrix:
        otp: [21, 22, 23, 24, 25, 26, 27]
    steps:
      - uses: actions/checkout@v4
      - run: rebar3 --version
      - run: rebar3 eunit
      - run: rebar3 dialyzer
